package com.thais.terrrarium_api.enums;

public enum EVENTS {
    WATER_ADDED,
    LIGHT_INCREASED,
    LIGHT_DECREASED,
    NUTRIENTS_ADDED,
    HUMIDITY_INCREASED,
    HUMIDITY_DECREASED,
    MOSS_EXPANDED,
    PLANT_GREW,
    FUNGUS_SPREAD,
    ORGANISM_SPAWNED,
    ORGANISM_DIED,
    MUTATION_OCCURRED,
    ECOSYSTEM_STABILIZED,
    ECOSYSTEM_COLLAPSED
}
